### ISSUE TITLE
큰 건 아니지만.. 해옫ㅇ  ==> 행동 인 것 같네용 :-)

### ISSUE THREAD

**Issue by tigerk0430** [rlcode/reinforcement-learning-kr#10]
https://github.com/rlcode/reinforcement-learning-kr/blob/4d6e004ba4834af5cd8255ae0f647e1f6b6e45ac/1-grid-world/2-value-iteration/value_iteration.py#L35

**Comment by keon** [comment]
1c200172c1f30add3aad3a631a5a7dbdfd886b85
반영하였습니다. 감사합니다!
