### ISSUE TITLE
SARSA 코드 관련 질문 있습니다.

### ISSUE THREAD

**Issue by classicmania** [rlcode/reinforcement-learning-kr#12]
SARSA 코드를 아나콘다에 있는 주피터로 실행시킬려고 하는데요.

evrironment.py  부분을 먼저 실행시켰고 잘 작동됐습니다.

그런데 sarsa_agent.py 부분을 실행시킬려고 하는데 계속 "from environment" 부분이 잘못된 모듈이라고 나오네요. 이럴 때 어떻게 해야 하나요?

**Comment by wooridle** [comment]
sarsa_agent.py 파일과 environment.py 파일이 동일한 디렉토리에 있나요?

**Comment by classicmania** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-fa1a226ae949> in <module>()
      2 import random
      3 from collections import defaultdict
----> 4 from environment import Env
      5 
      6 

ModuleNotFoundError: No module named 'environment'


이렇게 오류가 계속 뜹니다.

같은 주피터 노트북에 실행 시켜도 이렇게 나오고 
environment.py과 sarsa_agent.py 를 따로 실행 시켜도 
environment.py 부분은 오류가 안나오는데 sarsa_agent.py 부분만 실행시키면 앞의 오류가 뜨네요.
어떻게 해결해야 하나요?

**Comment by keon** [comment]
빨리 답장못드려 죄송합니다. 
#15 에서 해결하도록 하겠습니다.
