### ISSUE TITLE
p.85 self.get_policy(state, action)

### ISSUE THREAD

**Issue by jihobak** [rlcode/reinforcement-learning-kr#17]
p.85 쪽에 아래 식이 두 번이 나옵니다.
value += self.get_policy(state, action)
부분이 모두
value += self.get_policy(state)[action]
이걸로 바뀌어야 할 것 같습니다. 맞나요?

**Comment by zzing0907** [comment]
두 식 모두 value += self.get_policy(state)[action] 이 맞습니다!
책에 오탈자가 많네요ㅠㅠ 죄송합니다. 오탈자 찾아주셔서 감사합니다!!
