### ISSUE TITLE
Installing issues for windows 10 from wiki folder.

### ISSUE THREAD

**Issue by cws7777** [rlcode/reinforcement-learning-kr#3]
안녕하세요.
wiki 폴더 안에 있는 윈도우 설치 (윈도우 10 권장)을 차례대로 설치하였는데요..
나머지는 다 설치를 완료 하였는데 keras, 텐서플로우 등등 10번 즉 pip install -r requirements.txt에서
에러가 발생합니다.
running setup.py installing for scipy .... error
![image](https://user-images.githubusercontent.com/12144129/30146830-50b9342e-93d5-11e7-8a73-526c441d523b.png)

이런식으로 뜨는데 왜그런지 알 수 있을까요...?

감사합니다.

**Comment by dnddnjs** [comment]
답장이 늦어서 죄송합니다. 윈도우에서는 scipy가 pip로 설치되지 않습니다. 다음 링크로 가셔서 본인에게 맞으시는 scipy 버전을 선택해서 다운로드 받으셔야합니다.
http://www.lfd.uci.edu/~gohlke/pythonlibs/

다운로드 받은 경로에서 pip install [다운받은 파일명]을 입력하시면 설치가 될 겁니다. 설치 설명을 수정하도록 하겠습니다!!
