### ISSUE TITLE
NSException in DeepSARSA example

### ISSUE THREAD

**Issue by frostornge** [rlcode/reinforcement-learning-kr#4]
안녕하세요.
DeepSARSA 예제를 실행할때 NSException이 발생하는데요, 왜 그런지 알 수 있을까요..?
MacOS를 사용하고 있습니다.
에러코드도 가져와봤습니다!

감사합니다.

``
Using TensorFlow backend.
2017-09-13 12:24:36.081 Python[41112:3824657] -[NSApplication _setup:]: unrecognized selector sent to instance 0x103955ce0
2017-09-13 12:24:36.085 Python[41112:3824657] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x103955ce0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff7d8d62cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff926e148d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7d957f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff7d848755 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fff7d8482a8 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x0000000107b00c02 TkpInit + 471
	6   Tk                                  0x0000000107a7c2a9 Tk_Init + 1794
	7   _tkinter.cpython-35m-darwin.so      0x0000000104befdcd Tcl_AppInit + 77
	8   _tkinter.cpython-35m-darwin.so      0x0000000104bed7d9 _tkinter_create + 889
	9   Python                              0x0000000100065479 PyCFunction_Call + 233
	10  Python                              0x00000001000f1631 PyEval_EvalFrameEx + 36305
	11  Python                              0x00000001000f2510 _PyEval_EvalCodeWithName + 2368
	12  Python                              0x00000001000f038b PyEval_EvalFrameEx + 31531
	13  Python                              0x00000001000f2510 _PyEval_EvalCodeWithName + 2368
	14  Python                              0x00000001000f2617 PyEval_EvalCodeEx + 71
	15  Python                              0x000000010004031a function_call + 186
	16  Python                              0x000000010000d713 PyObject_Call + 99
	17  Python                              0x00000001000286fc method_call + 140
	18  Python                              0x000000010000d713 PyObject_Call + 99
	19  Python                              0x0000000100082a01 slot_tp_init + 81
	20  Python                              0x0000000100079624 type_call + 212
	21  Python                              0x000000010000d713 PyObject_Call + 99
	22  Python                              0x00000001000ec852 PyEval_EvalFrameEx + 16370
	23  Python                              0x00000001000f2510 _PyEval_EvalCodeWithName + 2368
	24  Python                              0x00000001000f2671 PyEval_EvalCode + 81
	25  Python                              0x000000010012083e PyRun_FileExFlags + 206
	26  Python                              0x0000000100120adf PyRun_SimpleFileExFlags + 447
	27  Python                              0x0000000100139858 Py_Main + 3512
	28  Python                              0x0000000100000e32 Python + 3634
	29  Python                              0x0000000100000c84 Python + 3204
	30  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
``

**Comment by Hyeokreal** [comment]
안녕하세요!

혹시 어떤 환경에서 작업하고 계신지 알 수 있을가요?
PyCharm 인지, IDLE인지 터미널로 실행하시는지 알면 해결하는데 더 도움이 될것 같아요!

**Comment by frostornge** [comment]
PyCharm에서 작업하고 있습니다
Python 버전은 3.7을 사용하고 있는데, 이것때문일까요?

**Comment by keon** [comment]
@frostornge 
넵 파이썬 3.7 버전이 prerelease상태라 텐서플로가 아직 지원하지 않는 것 같습니다.
파이썬 버전 3.5나 3.6으로 다시 설치해보시면 될것 같아요.

**Comment by frostornge** [comment]
아 감사합니다!
