### ISSUE TITLE
Definition of entropy in A3C code

### ISSUE THREAD

**Issue by rightx2** [rlcode/reinforcement-learning-kr#6]
A3C코드에 보면, `entropy` 는 다음과 같이 정의되어 있습니다.
```
entropy = K.sum(policy * K.log(policy + 1e-10), axis=1)
entropy = K.sum(entropy)
```
근데, 이 `entropy`에 -1을 곱하지 않는 이유가 궁금합니다. 지금 네트워크에서 이 entropy를 minimize를 하려는 것이 목표라면, -1을 붙여줘야 GradientDecent를 통해서 minimum 값으로 줄여갈 수 있지 않나요? 
(entropy의 정의는  `-p * logp`이고,  이 자체의 의미가 "정보를 최적으로 담을 수 있는 bit수" 이기 때문에, 이를 minimize하는 것이 목표가 되고, 이를 위해서는 위의 코드에 -1를 붙여줘야 된다고 생각합니다)

제 생각이 틀리다면, 지적 부탁드립니다 

감사합니다

**Comment by zzing0907** [comment]
entropy항은 exploration을 위한 항이기 때문에
maximize해야합니다. 정보이론쪽은 익숙치 않지만 좀 더 랜덤한 방향이 되려면 entropy를 크게 만들어줘야 된다고 알고있습니다. 

원래는 코드에서 두부분 다 (-)를 붙여줘야 정확한데 편의상 (-)는 빼줬습니다.

감사합니다.

**Comment by rightx2** [comment]
아.. 제가 그래프를 착각을 했습니다. 답변 감사합니다!
