### ISSUE TITLE
deep sarsa 실행시 tkinter  오류

### ISSUE THREAD

**Issue by adonisues** [rlcode/reinforcement-learning-kr#7]
안녕하세요 
책을 읽으며 실습을 진행하는 중에  제공해주신 코드실행시 오류가 발생하여 문의 드립니다.
OS Mac 10.12.6 
실행 : python3 deep_sarsa_agent.py
python 버전 : Python 3.5.4
오류 내용은 아래와 같습니다.

Using TensorFlow backend.
2017-10-22 23:50:08.979 Python[1081:14831] -[NSApplication _setup:]: unrecognized selector sent to instance 0x103be1c80
2017-10-22 23:50:08.980 Python[1081:14831] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x103be1c80'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffa4c7d2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffb9a9548d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffa4cfef04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fffa4bef755 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fffa4bef2a8 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x0000000106f76c02 TkpInit + 471
	6   Tk                                  0x0000000106ef22a9 Tk_Init + 1794
	7   _tkinter.cpython-35m-darwin.so      0x0000000106dcadcd Tcl_AppInit + 77
	8   _tkinter.cpython-35m-darwin.so      0x0000000106dc87d9 _tkinter_create + 889
	9   Python                              0x0000000100065cd9 PyCFunction_Call + 233
	10  Python                              0x00000001000f3e34 PyEval_EvalFrameEx + 38500
	11  Python                              0x00000001000f48a0 _PyEval_EvalCodeWithName + 2400
	12  Python                              0x00000001000f228a PyEval_EvalFrameEx + 31418
	13  Python                              0x00000001000f48a0 _PyEval_EvalCodeWithName + 2400
	14  Python                              0x00000001000f49a7 PyEval_EvalCodeEx + 71
	15  Python                              0x000000010004084a function_call + 186
	16  Python                              0x000000010000d783 PyObject_Call + 99
	17  Python                              0x000000010002886c method_call + 140
	18  Python                              0x000000010000d783 PyObject_Call + 99
	19  Python                              0x0000000100083a81 slot_tp_init + 81
	20  Python                              0x000000010007a3c4 type_call + 212
	21  Python                              0x000000010000d783 PyObject_Call + 99
	22  Python                              0x00000001000effb4 PyEval_EvalFrameEx + 22500
	23  Python                              0x00000001000f48a0 _PyEval_EvalCodeWithName + 2400
	24  Python                              0x00000001000f4a01 PyEval_EvalCode + 81
	25  Python                              0x0000000100122b7e PyRun_FileExFlags + 206
	26  Python                              0x0000000100122e2f PyRun_SimpleFileExFlags + 463
	27  Python                              0x000000010013bd12 Py_Main + 3554
	28  Python                              0x0000000100000e32 Python + 3634
	29  Python                              0x0000000100000c84 Python + 3204
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

pip3 list
bleach (1.5.0)
certifi (2017.7.27.1)
chardet (3.0.4)
cycler (0.10.0)
decorator (4.1.2)
gym (0.9.4)
h5py (2.7.1)
html5lib (0.9999999)
idna (2.6)
Keras (2.0.8)
Markdown (2.6.9)
matplotlib (2.1.0)
networkx (2.0)
numpy (1.13.3)
olefile (0.44)
pandas (0.20.3)
Pillow (4.3.0)
pip (9.0.1)
protobuf (3.4.0)
pyglet (1.2.4)
pyparsing (2.2.0)
python-dateutil (2.6.1)
pytz (2017.2)
PyWavelets (0.5.2)
PyYAML (3.12)
requests (2.18.4)
scikit-image (0.13.1)
scipy (0.19.1)
setuptools (36.6.0)
six (1.11.0)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.8)
urllib3 (1.22)
Werkzeug (0.12.2)
wheel (0.30.0)

감사합니다.

**Comment by wooridle** [comment]
Matplotlib 관련 오류일 것 같습니다.. 일단 그래프관련 라이브러리를 제외하고 실행하시면 될것 같습니다.

**Comment by kekmodel** [comment]
import pylab 라인을 지우고

import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as pylab

추가해서 해결했습니다.
